import React from 'react'
import { Typography, Box, Container, Grid } from '@mui/material'
import { useTheme, } from '@mui/material/styles';
import Fade from 'react-reveal/Fade';
import { makeStyles } from "@mui/styles";

const useStyles = makeStyles((theme) => ({
    image: {
        marginTop: '100px',
        [theme.breakpoints.down(700)]: {
            marginTop: '50px',
            width: "100%",
        },
    },
}));

const CryptoExp = () => {
    const classes = useStyles();
    const theme = useTheme();
    const color = theme.palette.mode;

    return (
        <>
            <Box sx={{ background: color == "light" ? '#7E64FF' : '#1F1F1E' }}>
                <Container fixed sx={{ paddingTop: { md: '150px', xs: '50px' }, paddingBottom: { md: '150px', xs: '50px' } }}>
                    <Typography sx={{ fontSize: { md: '64px', xs: '40px' }, lineHeight: { md: '98px', xs: '49px' }, fontWeight: '600', textAlign: 'center' }} color="#fff">
                        What are Crypto Express<br /> Trading Signals
                    </Typography>
                    <br />
                    <Typography sx={{ fontSize: '24px', lineHeight: '34px', fontWeight: '500', textAlign: 'center' }} color="#fff">
                        Crypto Express’s trading signals are generated by our proprietary algorithms which are combined with market analysis. Our team of traders and analysts have been working together for years, so we know what works and what doesn’t. We have a proven track record of over 90% accuracy on all major pairs, ensuring that our members always have consistent profits in their accounts. We use a variety of tools to evaluate the markets and find our best opportunities.
                    </Typography>
                    <br />
                    <Box display="flex" justifyContent="space-between" flexWrap="wrap">
                        <Typography sx={{ fontSize: '20px', lineHeight: '34px', fontWeight: '500', textAlign: 'center' }} color="#fff">
                            -Price Action Trading (TA)
                        </Typography>
                        <Typography sx={{ fontSize: '20px', lineHeight: '34px', fontWeight: '500', textAlign: 'center' }} color="#fff">
                            -Technical Analysis (TA)
                        </Typography>
                        <Typography sx={{ fontSize: '20px', lineHeight: '34px', fontWeight: '500', textAlign: 'center' }} color="#fff">
                            -Fundamental Analysis (FA)
                        </Typography>
                        <Typography sx={{ fontSize: '20px', lineHeight: '34px', fontWeight: '500', textAlign: 'center' }} color="#fff">
                            -Social Media Monitoring
                        </Typography>
                    </Box>
                    <Box textAlign="center">
                        <img src={require("../assets/Group 51.png")} alt="imf" className={classes.image} />
                    </Box>
                </Container>
            </Box>
        </>
    )
}


export default CryptoExp
